using Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Infrastructure.Configurations
{
    public class Subjects_Configurations : IEntityTypeConfiguration<Subject>
    {
        public void Configure(EntityTypeBuilder<Subject> builder)
        {
            builder.HasData(
                new Subject { code = "AI 310", course_Name_en = "Artificial Intelligence", hours = 3 },
                new Subject { code = "AI 320", course_Name_en = "Convex Optimization Theory", hours = 3 },
                new Subject { code = "AI 330", course_Name_en = "Machine Learning", hours = 3 },
                new Subject { code = "AI 335", course_Name_en = "Neural Networks & Deep Learning", hours = 3 },
                new Subject { code = "AI 350", course_Name_en = "Data Visualization", hours = 3 },
                new Subject { code = "AI 360", course_Name_en = "Natural Language Processing", hours = 3 },
                new Subject { code = "AI 370", course_Name_en = "Advanced Machine Learning", hours = 3 },
                new Subject { code = "AI 380", course_Name_en = "Human Computer Interaction", hours = 3 },
                new Subject { code = "AI 420", course_Name_en = "Evolutionary Algorithm", hours = 3 },
                new Subject { code = "AI 430", course_Name_en = "Computational Intelligence", hours = 3 },
                new Subject { code = "AI 435", course_Name_en = "Spoken Language Processing", hours = 3 },
                new Subject { code = "AI 457", course_Name_en = "Knowledge Representation", hours = 3 },
                new Subject { code = "AI 460", course_Name_en = "Natural Language Understanding", hours = 3 },
                new Subject { code = "AI 490", course_Name_en = "Bioinformatics", hours = 3 },
                new Subject { code = "AI 496", course_Name_en = "Selected Topics in Artificial Intelligence", hours = 3 },
                new Subject { code = "AI 498", course_Name_en = "Project", hours = 6 },
                new Subject { code = "CS 111", course_Name_en = "Introduction to Computers", hours = 3 },
                new Subject { code = "CS 112", course_Name_en = "Programming-1", hours = 3 },
                new Subject { code = "CS 213", course_Name_en = "Programming-2", hours = 3 },
                new Subject { code = "CS 214", course_Name_en = "Data Structures", hours = 3 },
                new Subject { code = "CS 221", course_Name_en = "Logic Design", hours = 3 },
                new Subject { code = "CS 241", course_Name_en = "Operating Systems-1", hours = 3 },
                new Subject { code = "CS 251", course_Name_en = "Software Engineering-1", hours = 3 },
                new Subject { code = "CS 313", course_Name_en = "Programming-3", hours = 3 },
                new Subject { code = "CS 316", course_Name_en = "Algorithms", hours = 3 },
                new Subject { code = "CS 322", course_Name_en = "Computer Organization", hours = 3 },
                new Subject { code = "CS 342", course_Name_en = "Operating Systems-2", hours = 3 },
                new Subject { code = "CS 352", course_Name_en = "Software Engineering-2", hours = 3 },
                new Subject { code = "CS 405", course_Name_en = "Theory of Computation", hours = 3 },
                new Subject { code = "CS 410", course_Name_en = "Concepts of Programming Languages", hours = 3 },
                new Subject { code = "CS 416", course_Name_en = "Advanced Algorithms", hours = 3 },
                new Subject { code = "CS 419", course_Name_en = "Compilers", hours = 3 },
                new Subject { code = "CS 460", course_Name_en = "Distributed Systems and Cloud Computing", hours = 3 },
                new Subject { code = "CS 471", course_Name_en = "Parallel Processing and High Performance Computing", hours = 3 },
                new Subject { code = "CS 480", course_Name_en = "Cryptography", hours = 3 },
                new Subject { code = "CS 496", course_Name_en = "Selected Topics in Computer Science", hours = 3 },
                new Subject { code = "CS 498", course_Name_en = "Project", hours = 6 },
                new Subject { code = "HU 111", course_Name_en = "English-1", hours = 2 },
                new Subject { code = "HU 112", course_Name_en = "English-2", hours = 2 },
                new Subject { code = "HU 121", course_Name_en = "Fundamentals of Economics", hours = 3 },
                new Subject { code = "HU 122", course_Name_en = "Fundamentals of Management", hours = 3 },
                new Subject { code = "HU 213", course_Name_en = "English-3", hours = 3 },
                new Subject { code = "HU 313", course_Name_en = "Human Rights", hours = 2 },
                new Subject { code = "HU 323", course_Name_en = "Fundamentals of Accounting", hours = 3 },
                new Subject { code = "HU 331", course_Name_en = "Communication & Negotiation Skills", hours = 3 },
                new Subject { code = "HU 332", course_Name_en = "Creative Thinking", hours = 3 },
                new Subject { code = "HU 333", course_Name_en = "Mass Communication", hours = 3 },
                new Subject { code = "HU 334", course_Name_en = "Professional Ethics", hours = 3 },
                new Subject { code = "IS 211", course_Name_en = "Database Systems-1", hours = 3 },
                new Subject { code = "IS 231", course_Name_en = "Fundamentals of Information Systems", hours = 3 },
                new Subject { code = "IS 240", course_Name_en = "Operations Research", hours = 3 },
                new Subject { code = "IS 241", course_Name_en = "Modeling and Simulation", hours = 3 },
                new Subject { code = "IS 312", course_Name_en = "Database Systems-2", hours = 3 },
                new Subject { code = "IS 313", course_Name_en = "Data Storage and Retrieval", hours = 3 },
                new Subject { code = "IS 321", course_Name_en = "Projects Management", hours = 3 },
                new Subject { code = "IS 333", course_Name_en = "Management Information Systems", hours = 3 },
                new Subject { code = "IS 334", course_Name_en = "Accounting Information Systems", hours = 3 },
                new Subject { code = "IS 342", course_Name_en = "Simulation Languages", hours = 3 },
                new Subject { code = "IS 345", course_Name_en = "Internet Applications", hours = 3 },
                new Subject { code = "IS 350", course_Name_en = "Business Intelligence and Data Analytical", hours = 3 },
                new Subject { code = "IS 351", course_Name_en = "System Analysis and Design-1", hours = 3 },
                new Subject { code = "IS 352", course_Name_en = "Analysis and Design of Information Systems-2", hours = 3 },
                new Subject { code = "IS 360", course_Name_en = "Introduction to Data Science", hours = 3 },
                new Subject { code = "IS 365", course_Name_en = "Big Data Technologies", hours = 3 },
                new Subject { code = "IS 414", course_Name_en = "Information Systems Security", hours = 3 },
                new Subject { code = "IS 415", course_Name_en = "Object Oriented Database", hours = 3 },
                new Subject { code = "IS 416", course_Name_en = "Distributed Database", hours = 3 },
                new Subject { code = "IS 421", course_Name_en = "Data Mining", hours = 3 },
                new Subject { code = "IS 422", course_Name_en = "Data Warehousing", hours = 3 },
                new Subject { code = "IS 434", course_Name_en = "Quality Assurance of Information Systems and Programming", hours = 3 },
                new Subject { code = "IS 435", course_Name_en = "Information Centers Management", hours = 3 },
                new Subject { code = "IS 441", course_Name_en = "Intelligent Information Systems", hours = 3 },
                new Subject { code = "IS 442", course_Name_en = "E-Commerce", hours = 3 },
                new Subject { code = "IS 443", course_Name_en = "Geographical Information Systems", hours = 3 },
                new Subject { code = "IS 444", course_Name_en = "Multimedia Information Systems", hours = 3 },
                new Subject { code = "IS 448", course_Name_en = "Knowledge base management", hours = 3 },
                new Subject { code = "IS 450", course_Name_en = "Software Testing and Integration", hours = 3 },
                new Subject { code = "IS 451", course_Name_en = "Decision Support Systems", hours = 3 },
                new Subject { code = "IS 453", course_Name_en = "Information Systems Development Methodologies", hours = 3 },
                new Subject { code = "IS 455", course_Name_en = "Software Quality Assurance and Testing", hours = 3 },
                new Subject { code = "IS 460", course_Name_en = "Introduction to Deep Learning", hours = 3 },
                new Subject { code = "IS 496", course_Name_en = "Selected Topics in Information Systems", hours = 3 },
                new Subject { code = "IS 498", course_Name_en = "Project", hours = 6 },
                new Subject { code = "IT 111", course_Name_en = "Electronics-1", hours = 3 },
                new Subject { code = "IT 211", course_Name_en = "Computer Maintenance", hours = 3 },
                new Subject { code = "IT 221", course_Name_en = "Data Communication", hours = 3 },
                new Subject { code = "IT 222", course_Name_en = "Computer Networks-1", hours = 3 },
                new Subject { code = "IT 223", course_Name_en = "Internet Technology", hours = 3 },
                new Subject { code = "IT 241", course_Name_en = "Signals and Systems", hours = 3 },
                new Subject { code = "IT 311", course_Name_en = "Computer Architecture", hours = 3 },
                new Subject { code = "IT 312", course_Name_en = "Microprocessors", hours = 3 },
                new Subject { code = "IT 313", course_Name_en = "Computer Interfaces", hours = 3 },
                new Subject { code = "IT 321", course_Name_en = "Communication Technology", hours = 3 },
                new Subject { code = "IT 322", course_Name_en = "Computers Network-2", hours = 3 },
                new Subject { code = "IT 331", course_Name_en = "Computer Graphics-1", hours = 3 },
                new Subject { code = "IT 332", course_Name_en = "Computer Graphics-2", hours = 3 },
                new Subject { code = "IT 341", course_Name_en = "Digital Signal Processing", hours = 3 },
                new Subject { code = "IT 342", course_Name_en = "Pattern Recognition", hours = 3 },
                new Subject { code = "IT 411", course_Name_en = "Distributed and Parallel Computer Systems", hours = 3 },
                new Subject { code = "IT 412", course_Name_en = "Real Time Systems", hours = 3 },
                new Subject { code = "IT 414", course_Name_en = "Embedded Systems", hours = 3 },
                new Subject { code = "IT 415", course_Name_en = "Robotics", hours = 3 },
                new Subject { code = "IT 422", course_Name_en = "Wireless and Mobile Networks", hours = 3 },
                new Subject { code = "IT 423", course_Name_en = "Information and Computer Networks Security", hours = 3 },
                new Subject { code = "IT 425", course_Name_en = "Embedded Internet of Things System", hours = 3 },
                new Subject { code = "IT 431", course_Name_en = "Virtual Reality", hours = 3 },
                new Subject { code = "IT 433", course_Name_en = "Multimedia", hours = 3 },
                new Subject { code = "IT 441", course_Name_en = "Image Processing-1", hours = 3 },
                new Subject { code = "IT 442", course_Name_en = "Image Processing-2", hours = 3 },
                new Subject { code = "IT 443", course_Name_en = "Speech Processing", hours = 3 },
                new Subject { code = "IT 444", course_Name_en = "Computer Vision", hours = 3 },
                new Subject { code = "IT 455", course_Name_en = "Image, Audio and Video Processing", hours = 3 },
                new Subject { code = "IT 456", course_Name_en = "3D Modeling and Animation", hours = 3 },
                new Subject { code = "IT 457", course_Name_en = "Game Development", hours = 3 },
                new Subject { code = "IT 496", course_Name_en = "Selected Topics in Information Technology", hours = 3 },
                new Subject { code = "IT 498", course_Name_en = "Project", hours = 6 },
                new Subject { code = "MA 111", course_Name_en = "Mathematics-1", hours = 3 },
                new Subject { code = "MA 112", course_Name_en = "Discrete Mathematics", hours = 3 },
                new Subject { code = "MA 113", course_Name_en = "Mathematics-2", hours = 3 },
                new Subject { code = "PH 111", course_Name_en = "Physics", hours = 3 },
                new Subject { code = "ST 121", course_Name_en = "Probability and Statistics-1", hours = 3 },
                new Subject { code = "ST 122", course_Name_en = "Probability and Statistics-2", hours = 3 }
                );
        }
    }
}
